### ISSUE TITLE
I need your advice

### ISSUE THREAD

**Issue by vvpgrp** [derekisbusy/yii2-forcecopy#1]
I need your advice: how to use your extension for applications in which YII_DEBUG variable will load from a file. For example (please see https://github.com/trntv/yii2-starter-kit) a value of this variable is loading from .env file. 
Thanks you advance.

**Comment by derekisbusy** [comment]
This extension doesn't make use of YII_DEBUG constant. It is loaded as a panel of the [yii2debug](https://github.com/yiisoft/yii2-debug.git) extension.
